# Generated by Django 3.1.5 on 2021-02-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='ShoppingAddress',
        ),
    ]
