# Generated by Django 3.1.5 on 2021-02-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210204_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingAddress',
            new_name='ShippingAddress',
        ),
    ]
